#############################################################################
# Generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#  Nov 24, 2018 01:51:05 PM +0200  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {} -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 437x255+552+260
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "CDMA Transmitter "
    vTcl:DefineAlias "$top" "mainPage" vTcl:Toplevel:WidgetProc "" 1
    ttk::combobox $top.tCo48 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo48" "portOpt" vTcl:WidgetProc "mainPage" 1
    button $top.but49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Load img 0} 
    vTcl:DefineAlias "$top.but49" "loadB0" vTcl:WidgetProc "mainPage" 1
    button $top.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Load img 1} 
    vTcl:DefineAlias "$top.but50" "loadB1" vTcl:WidgetProc "mainPage" 1
    button $top.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Show images} 
    vTcl:DefineAlias "$top.but51" "showB" vTcl:WidgetProc "mainPage" 1
    button $top.but52 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Encode data} 
    vTcl:DefineAlias "$top.but52" "encodeB" vTcl:WidgetProc "mainPage" 1
    button $top.but53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Send 
    vTcl:DefineAlias "$top.but53" "SendB" vTcl:WidgetProc "mainPage" 1
    ttk::combobox $top.tCo54 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo54" "SNR_opt" vTcl:WidgetProc "mainPage" 1
    canvas $top.can58 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 75 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can58" "img0C" vTcl:WidgetProc "mainPage" 1
    vTcl:copy_lock $top.can58
    canvas $top.can60 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 75 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can60" "img1C" vTcl:WidgetProc "mainPage" 1
    vTcl:copy_lock $top.can60
    button $top.but61 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Open port} 
    vTcl:DefineAlias "$top.but61" "openB" vTcl:WidgetProc "mainPage" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tCo48 \
        -in $top -x 20 -y 20 -width 81 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 20 -y 60 -width 81 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.275 -y 60 -width 81 -relwidth 0 -height 24 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 20 -y 0 -rely 0.4 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 20 -y 140 -width 81 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.275 -y 0 -rely 0.706 -width 81 -relwidth 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo54 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.706 -width 81 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $top.can58 \
        -in $top -x 270 -y 80 -width 50 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can60 \
        -in $top -x 350 -y 80 -width 50 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 120 -y 20 -width 81 -relwidth 0 -height 24 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

